#word collection
negative_words = {
    'bad':95,'hate':90,
    'angry':80,
    "abandon": 80,
    "betray": 85,
    "crisis": 90,
    "danger": 95,
    "enemy": 80,
    "failure": 95,
    "grief": 90,
    "harm": 85,
    "inferior": 80,
    "jealousy": 90,
    "killed": 95,
    "lose": 85,
    "mourn": 90,
    "negative": 80,
    "offend": 85,
    "pain": 90,
    "quit": 95,
    "reject": 85,
    "sorrow": 90,
    "terrible": 95,
    "nnhappy": 80,
    "vicious": 85,
    "worry": 90,
    "xenophobic": 95,
    "yearn": 80,
    "zealous": 85,
    "agony": 90,
    "blame": 95,
    "chaos": 80,
    "despair": 85,
    "dreadful": 90,
    "evil": 95,
    "forsaken": 80,
    "guilt": 85,
    "hatred": 90,
    "injure": 95,
    "jinxed": 80,
    "killjoy": 85,
    "lament": 90,
    "malice": 95,
    "nasty": 80,
    "obnoxious": 85,
    "pessimism": 90,
    "quarrel": 95,
    "ruthless": 80,
    "suffer": 85,
    "terror": 90,
    "unfortunate": 95,
    "vindictive": 80
    
}

positive_words = {
    'good':89,'best':95,'smart':80,
    'happy': 90,
    'joyful': 92,
    'exciting': 88,
    'wonderful': 91,
    'fantastic': 89,
    'excellent': 87,
    'great': 85,
    'amazing': 93,
    'awesome': 94,
    'delightful': 91,
    'beautiful': 88,
    'brilliant': 86,
    'superb': 90,
    'cheerful': 89,
    'positive': 85,
    'optimistic': 87,
    'success': 92,
    'victorious': 91,
    'love': 95,
    'admire': 90,
    'adore': 92,
    'appreciate': 88,
    'terrific': 89,
    'splendid': 91,
    'magnificent': 93,
    'glorious': 92,
    'fabulous': 90,
    'remarkable': 88,
    'outstanding': 89,
    'marvelous': 92,
    'exuberant': 90,
    'ecstatic': 93,
    'upbeat': 88,
    'jubilant': 91,
    'splendor': 89,
    'blissful': 94,
    'euphoric': 92,
    'festive': 90,
    'radiant': 91,
    'serene': 87,
    'uplifting': 89,
    'thrilled': 93,
    'positive': 90,
    'prosperous': 91,
    'sensational': 92,
    'stunning': 90,
}
stop_word = {
    'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", 
    "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 
    'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 
    'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 
    'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 
    'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 
    'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 
    'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 
    'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 
    'other', 'some', 'such', 'only', 'own', 'same', 'than', 's','am','hii','hello',
    't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 
    've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', 
    "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', 
    "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', 
    "weren't", 'won', "won't", 'wouldn', "wouldn't"
}